#! /bin/sh

set -e -u

cp -a bleach tests ${AUTOPKGTEST_TMP}

for py3vers in $(py3versions -s); do
    echo
    echo "***************************"
    echo "*** Testing with ${py3vers}"
    echo "***************************"
    echo
    cd ${AUTOPKGTEST_TMP} && \
        echo "Content of current working folder:\n" && \
        ls -la && \
        echo "Running tests...\n" && \
        ${py3vers} -m pytest -s tests && \
        rm -rf .pytest_cache || exit 1
done

rm -rf bleach

echo "\nTrying to import the bleach library from site-packages and getting the library version..."
python3 -c "import bleach; print(bleach.__version__)"
echo

exit 0
