name: build
on:
 push:
 pull_request:
 schedule:
#Every 5 days at midnight 
    - cron:  "0 0 1/20 * *"

jobs:
  compilejobFedora39:
    runs-on: ubuntu-latest
    name: Indico_on_Fedora39
    container:
        image: fedora:39
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      run: |
           set -x
           uname -a 
           cat /etc/issue
           dnf -y install dnf* rpm-build git wget sed createrepo wget
           dnf -y install python3-devel python3-setuptools python-srpm-macros python3-rpm-macros pyproject-rpm-macros
           dnf -y copr enable averbyts/I328
           export PATH=$PATH:$(pwd)
           set -x 
           sh srpmsbuild.sh  indico-devel 3.2.8 --build 
           yum -y install indico-devel/3.2.8/rpmbuild/RPMS/*/*.rpm --skip-broken
           mkdir -p /github/home/.npm
           chown -R 1001:121 "/github/home/.npm"
           sh srpmsbuild.sh  python-indico 3.2.8 --build 
           yum -y install wget  python-indico/3.2.8/rpmbuild/RPMS/*/*.rpm --skip-broken
