name: build
on:
 push:
 pull_request:
 schedule:
#Every 5 days at midnight 
    - cron:  "0 0 1/20 * *"

jobs:


  compilejobFedora36:
    runs-on: ubuntu-latest
    name: Indico_on_Fedora36
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compileindocker
      uses: ./.github/workflows/fedora36
    - name: Get the output status
      run: exit ${{ steps.compileindocker.outputs.out }}

  compilejobFedora37:
    runs-on: ubuntu-latest
    name: Indico_on_Fedora37
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compileindocker
      uses: ./.github/workflows/fedora37
    - name: Get the output status
      run: exit ${{ steps.compileindocker.outputs.out }}

