name: build
on:
 push:
 pull_request:
 schedule:
#Every 5 days at midnight 
    - cron:  "0 0 1/20 * *"

jobs:



  compilejobFedora38:
    runs-on: ubuntu-latest
    name: Indico_on_Fedora38
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compileindocker
      uses: ./.github/workflows/fedora38
    - name: Get the output status
      run: exit ${{ steps.compileindocker.outputs.out }}

