name: build
on:
 push:
 pull_request:
 schedule:
#Every 5 days at midnight 
    - cron:  "0 0 1/20 * *"

jobs:
  compilejobFedora39:
    runs-on: ubuntu-latest
    name: Indico_on_Fedora39
    container:
        image: fedora:39
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      run: |
           set -x
           uname -a 
           cat /etc/issue
           exit 0
           dnf -y install dnf-* rpm-build git wget sed createrepo wget
           dnf -y install python3-devel python3-setuptools python-srpm-macros python3-rpm-macros pyproject-rpm-macros
           dnf -y copr enable averbyts/I329
           dnf -y install indico-devel 
           export PATH=$PATH:$(pwd)
           #set -x 
           sh srpmsbuild.sh  python-indico 3.2.9 --build 
           #yum -y install indico-devel/3.2.9/rpmbuild/RPMS/*/*.rpm --skip-broken
           #mkdir -p /github/home/.npm
           #chown -R 1001:121 "/github/home/.npm"
           #sh srpmsbuild.sh  python-indico 3.2.9 --build 
           #yum -y install wget  python-indico/3.2.9/rpmbuild/RPMS/*/*.rpm --skip-broken


  compilejobDebian12:
    runs-on: ubuntu-latest
    name: Indico_on_Debian12
    container:
        image: debian:12
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      run: |
           set -x
           exit 0
           uname -a 
           cat /etc/issue
           apt-get update
           apt-get -y -q install wget  dpkg-dev
           apt-get -y -q install dh-python python3 python3-setuptools python3-pytest debhelper-compat  pybuild-plugin-pyproject flit
           apt-get -y -q install python3-typing-inspect python3-semver python3-pip python3-flask python3-ldap python3-pytest-runner python3-marshmallow
           apt-get -y -q install python3-lxml python3-limits python3-ordered-set python3-dateutil python3-sqlalchemy python3-wtforms python3-flaskext.wtf
           apt-get -y -q install unzip npm python3-yaml python3-celery python3-bleach python3-email-validator python3-markdown python3-translitcodec
           apt-get -y -q install unzip python3-html2text python3-sentry-sdk python3-authlib python3-flask-babel python3-speaklater python3-cachelib python3-flask-caching python3-redis python3-terminaltables python3-flask-sqlalchemy python3-jsonschema python3-ua-parser python3-colorclass python3-flask-marshmallow python3-marshmallow-sqlalchemy python3-marshmallow-enum python3-webargs python3-bcrypt python3-executing python3-pure-eval python3-reportlab python3-qrcode python3-icalendar python3-pycountry python3-xlsxwriter python3-distro

           export PATH=$PATH:$(pwd)
           bash debianalllocal.sh
           bash debiancompileindico.sh
