name: build
on:
 push:
 pull_request:
 schedule:
#Every 5 days at midnight 
    - cron:  "0 0 1/20 * *"

jobs:
  compilejobFedora39:
    runs-on: ubuntu-latest
    name: Indico_on_Fedora39
    container:
        image: fedora:39
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      run: |
           set -x
           uname -a 
           cat /etc/issue
           dnf -y install dnf-* rpm-build git wget sed createrepo wget
           dnf -y install python3-devel python3-setuptools python-srpm-macros python3-rpm-macros pyproject-rpm-macros
           dnf -y copr enable averbyts/I329
           export PATH=$PATH:$(pwd)
           #set -x 
           #sh srpmsbuild.sh  indico-devel 3.2.9 --build 
           #yum -y install indico-devel/3.2.9/rpmbuild/RPMS/*/*.rpm --skip-broken
           #mkdir -p /github/home/.npm
           #chown -R 1001:121 "/github/home/.npm"
           #sh srpmsbuild.sh  python-indico 3.2.9 --build 
           #yum -y install wget  python-indico/3.2.9/rpmbuild/RPMS/*/*.rpm --skip-broken


  compilejobDebian12:
    runs-on: ubuntu-latest
    name: Indico_on_Debian12
    container:
        image: debian:12
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      run: |
           set -x
           uname -a 
           cat /etc/issue
           apt-get update
           apt-get -y install wget  dpkg-dev
           apt-get -y install dh-python python3 python3-setuptools python3-pytest debhelper-compat  pybuild-plugin-pyproject flit
           apt-get -y install python3-typing-inspect python3-semver python3-pip python3-flask python3-ldap python3-pytest-runner python3-marshmallow
           apt-get -y install python3-lxml python3-limits python3-ordered-set python3-dateutil python3-sqlalchemy python3-wtforms python3-flaskext.wtf
           export TOP=$(pwd)
           export PATH=$PATH:$(pwd)
           cd DEB
           bash ../debianalllocal.sh
           apt-get -y install unzip npm
           mkdir COMPILE
           cd COMPILE/
           wget https://github.com/indico/indico/archive/refs/tags/v3.2.9.zip
           unzip -q v3.2.9.zip 
           wget https://github.com/indico/indico-plugins/archive/refs/tags/v3.2.2.tar.gz
           tar xf  v3.2.2.tar.gz 
           cd indico-3.2.9/
           cp -r $TOP/python-indico/3.2.9/PATCHED/* ./
           mkdir -p plugins
           mv ../indico-plugins-3.2.2/ plugins/base
           rm -rf plugins/base/piwik
           rm -rf plugins/base/themes_legacy
           rm -rf plugins/base/ursh
           rm -rf plugins/base/vc_zoom
           rm -rf plugins/base/cloud_captchas
           rm -rf plugins/base/owncloud
           rm -rf plugins/base/previewer_jupyter
           sed -i 's/iso4217\=\=.*$/iso4217/g'     plugins/base/*/setup.cfg
           sed -i 's/nbconvert\=\=.*$/nbconvert/g' plugins/base/*/setup.cfg
           sed -i 's/indico-plugin-piwik.*$//g'    plugins/base/_meta/setup.cfg
           sed -i 's/indico-plugin-ursh.*$//g'     plugins/base/_meta/setup.cfg
           sed -i 's/indico-plugin-vc-zoom.*$//g'  plugins/base/_meta/setup.cfg
           sed -i 's/indico-plugin-cloud-captchas.*$//g'  plugins/base/_meta/setup.cfg
           sed -i 's/indico-plugin-owncloud.*$//g'  plugins/base/_meta/setup.cfg
           sed -i 's/indico-plugin-previewer-jupyter.*$//g'  plugins/base/_meta/setup.cfg
           sed -i 's/\=\=.*$//g' requirements.*
           sed -i 's/tzdata/#tzdata/g' requirements.*
           sed -i 's/pypdf/#pypdf/g' requirements.*
           sed -i 's/importlib/#importlib/g' requirements.*
           export NODE_OPTIONS="--max-old-space-size=5120"
           export PYTHONPATH=$(pwd):$PYTHONPATH
           mkdir -p indico/web/client
           cd indico/web/client
           npm install
           cd ../../../
           npm install
           ./bin/maintenance/build-wheel.py indico       --ignore-unclean 
           ./bin/maintenance/build-wheel.py all-plugins  --ignore-unclean  plugins/base

