name: publish
on: 
  push:
  pull_request:  
  schedule:
    - cron: "0 7 * * 2"
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
   contents: read
   pages: write
   id-token: write
   packages: write

#permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:


  build-indico-docker-image-Fedora42:
    runs-on: ubuntu-latest
    name: Fedora image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 2 
    - name: Check if the Docker file was changed
      id: changed-docker-files
      uses: tj-actions/changed-files@v38
      with:
          files: Fedora42

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the indico Docker image on the change of Dockerfile
      if: steps.changed-docker-files.outputs.any_changed == 'true' 
      run: |
         docker build . -f Fedora42 --tag ghcr.io/andriish/indicofedora42:latest
         docker run ghcr.io/andriish/indicofedora42:latest
         docker push ghcr.io/andriish/indicofedora42:latest
    - name: Build the indico Docker image on schedule
      if: ${{ github.event_name == 'schedule' }}
      run: |
         docker build . -f Fedora42 --tag ghcr.io/andriish/indicofedora42:latest
         docker run ghcr.io/andriish/indicofedora42:latest
         docker push ghcr.io/andriish/indicofedora42:latest
  build-indico-docker-image-Fedora43:
    runs-on: ubuntu-latest
    name: Fedora image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 2 
    - name: Check if the Docker file was changed
      id: changed-docker-files
      uses: tj-actions/changed-files@v38
      with:
          files: Fedora43

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the indico Docker image on the change of Dockerfile
      if: steps.changed-docker-files.outputs.any_changed == 'true' 
      run: |
         docker build . -f Fedora43 --tag ghcr.io/andriish/indicofedora43:latest
         docker run ghcr.io/andriish/indicofedora43:latest
         docker push ghcr.io/andriish/indicofedora43:latest
    - name: Build the indico Docker image on schedule
      if: ${{ github.event_name == 'schedule' }}
      run: |
         docker build . -f Fedora43 --tag ghcr.io/andriish/indicofedora43:latest
         docker run ghcr.io/andriish/indicofedora43:latest
         docker push ghcr.io/andriish/indicofedora43:latest
  #build-indico-docker-image-Debian12:
    #runs-on: ubuntu-latest
    #name: Debian image
    #steps:
    #- name: Checkout
      #uses: actions/checkout@v3
      #with:
          #fetch-depth: 2 
    #- name: Check if the Docker file was changed
      #id: changed-docker-files
      #uses: tj-actions/changed-files@v38
      #with:
          #files: Debian12

    #- name: Login to GitHub Container Registry
      #uses: docker/login-action@v2
      #with:
        #registry: ghcr.io
        #username: ${{ github.actor }}
        #password: ${{ secrets.GITHUB_TOKEN }}
    #- name: Build the indico Docker image on the change of Dockerfile
      #if: steps.changed-docker-files.outputs.any_changed == 'true' 
      #run: |
         #docker build . -f Debian12 --tag ghcr.io/andriish/indicodebian12:latest
         #docker run ghcr.io/andriish/indicodebian12:latest
         #docker push ghcr.io/andriish/indicodebian12:latest
    #- name: Build the indico Docker image on schedule
      #if: ${{ github.event_name == 'schedule' }}
      #run: |
         #docker build . -f Debian12 --tag ghcr.io/andriish/indicodebian12:latest
         #docker run ghcr.io/andriish/indicodebian12:latest
         #docker push ghcr.io/andriish/indicodebian12:latest


  run-in-indico-docker-image-Fedora42:
    name: Fedora
    runs-on: ubuntu-latest
    needs: build-indico-docker-image-Fedora42
    container:
            image: ghcr.io/andriish/indicofedora42:latest
            credentials:
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 3 
    - name: Run
      run : |
           set -x
           uname -a 
           cat /etc/issue      
           cd RPM
           bash rpm_alllocal.sh
           ls ./*/*/rpmbuild/RPMS/*/*.rpm
           cd ..
           mkdir -p myrepo/Fedora42
           cp RPM/*/*/rpmbuild/RPMS/*/*.rpm myrepo/Fedora42
           yum -y install createrepo
           createrepo myrepo/Fedora42
           ls -lah myrepo/Fedora42
           tar   -cvf artifact-Fedora42.tar myrepo
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name:  Fedora42af
          path: artifact-Fedora42.tar
  
  
  #run-in-indico-docker-image-Debian12:
    #name: Debian
    #runs-on: ubuntu-latest
    #needs: build-indico-docker-image-Debian12
    #container:
            #image: ghcr.io/andriish/indicodebian12:latest
            #credentials:
               #username: ${{ github.actor }}
               #password: ${{ secrets.GITHUB_TOKEN }}
    #steps:
    #- name: Checkout
      #uses: actions/checkout@v4
      #with:
          #fetch-depth: 3          
    #- name: Run
      #run : |
           #set -x
           #uname -a 
           #cat /etc/issue
           #apt-get update
           #cd DEB
           #bash deb_alllocal.sh
           #cd ..
           #ls DEB/*/*/mydbtop/*deb
           #mkdir -p myrepo/Debian12
           #cp DEB/*/*/mydbtop/*deb myrepo/Debian12
           #apt-get -y install  dpkg-dev 
           #cd  myrepo/Debian12
           #dpkg-scanpackages . /dev/null > Release
           #cd ../../
           #tar   -cvf artifact-Debian12.tar myrepo
    #- name: Upload artifact
      #uses: actions/upload-artifact@v4
      #with:
          #name:  Debian12af
          #path: artifact-Debian12.tar
  
  #deploy-from-all:
    #name: Deploy
    #runs-on: ubuntu-latest    
    #environment:
      #name: github-pages
      #url: ${{ steps.deployment.outputs.page_url }}  
    #needs: 
     #- run-in-indico-docker-image-Debian12
     #- run-in-indico-docker-image-Fedora42
    #steps:
    #- uses: actions/download-artifact@v4
      #with:
          #name: Fedora42af
          #path: myrepo
    #- uses: actions/download-artifact@v4
      #with:
          #name: Debian12af
          #path: myrepo
    #- name: Display structure of downloaded files
      #run: |
          #ls -R myrepo
          #cd  myrepo
          #tar -xf artifact-Debian12.tar
          #tar -xf artifact-Fedora42.tar
          #mv myrepo indico330
          #ls 
          #rm ./*.tar -f
          #cd ..
    #- uses: jayanta525/github-pages-directory-listing@v4.0.0
      #with:
          #FOLDER: ./myrepo      
    #- name: Upload artifact
      #uses: actions/upload-pages-artifact@v3
      #with:
          ## Upload entire repository
          #path: ./myrepo
    #- name: Deploy to GitHub Pages
      #id: deployment
      #uses: actions/deploy-pages@v4

  
