name: publish
on: 
  push:
  pull_request:  
  schedule:
    - cron: "0 7 * * 2"
jobs:
  build-indico-docker-image-Debian12:
    runs-on: ubuntu-latest
    name: Build indico Docker image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 2 
    - name: Check if the Docker file was changed
      id: changed-docker-files
      uses: tj-actions/changed-files@v38
      with:
          files: Debian12

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the indico Docker image on the change of Dockerfile
      if: steps.changed-docker-files.outputs.any_changed == 'true' 
      run: |
         docker build . -f Debian12 --tag ghcr.io/andriish/indicodebian12:latest
         docker run ghcr.io/andriish/indicodebian12:latest
         docker push ghcr.io/andriish/indico-rpms
    - name: Build the indico Docker image on schedule
      if: ${{ github.event_name == 'schedule' }}
      run: |
         docker build . -f Debian12 --tag ghcr.io/andriish/indicodebian12:latest
         docker run ghcr.io/andriish/indicodebian12:latest
         docker push ghcr.io/andriish/indico-rpms


  build-indico-docker-image-Fedora39:
    runs-on: ubuntu-latest
    name: Build indico Docker image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 2 
    - name: Check if the Docker file was changed
      id: changed-docker-files
      uses: tj-actions/changed-files@v38
      with:
          files: Fedora39

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the indico Docker image on the change of Dockerfile
      if: steps.changed-docker-files.outputs.any_changed == 'true' 
      run: |
         docker build . -f Fedora39 --tag ghcr.io/andriish/indicofedora39:latest
         docker run ghcr.io/andriish/indicofedora39:latest
         docker push ghcr.io/andriish/indico-rpms
    - name: Build the indico Docker image on schedule
      if: ${{ github.event_name == 'schedule' }}
      run: |
         docker build . -f Fedora39 --tag ghcr.io/andriish/indicofedora39:latest
         docker run ghcr.io/andriish/indicofedora39:latest
         docker push ghcr.io/andriish/indico-rpms






  run-in-indico-docker-image-Fedora39:
    name: Run in indico Docker image  with gmake
    runs-on: ubuntu-latest
    needs: build-indico-docker-image-Fedora39
    container:
            image: ghcr.io/andriish/indicofedora39:latest
            credentials:
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 3 
    - name: Run
      run : |
           export PATH=$PATH:$(pwd)
           #set -x 
           sh srpmsbuild.sh  python-indico 3.2.9 --build 
  
  run-in-indico-docker-image-Debian12:
    name: Run in indico Docker image  with gmake
    runs-on: ubuntu-latest
    needs: build-indico-docker-image-Debian12
    container:
            image: ghcr.io/andriish/indicodebian12:latest
            credentials:
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 3 
    - name: Run
      run : |
           set -x
           uname -a 
           cat /etc/issue
           apt-get update
           apt-get -y -q install wget  dpkg-dev
           apt-get -y -q install dh-python python3 python3-setuptools python3-pytest debhelper-compat  pybuild-plugin-pyproject flit
           apt-get -y -q install python3-typing-inspect python3-semver python3-pip python3-flask python3-ldap python3-pytest-runner python3-marshmallow
           apt-get -y -q install python3-lxml python3-limits python3-ordered-set python3-dateutil python3-sqlalchemy python3-wtforms python3-flaskext.wtf
           apt-get -y -q install unzip npm python3-yaml python3-celery python3-bleach python3-email-validator python3-markdown python3-translitcodec
           ##
           apt-get -y -q install unzip python3-html2text python3-sentry-sdk python3-authlib python3-flask-babel python3-speaklater python3-cachelib python3-flask-caching 
           apt-get -y -q install python3-redis python3-terminaltables python3-flask-sqlalchemy python3-jsonschema python3-ua-parser python3-colorclass 
           apt-get -y -q install python3-flask-marshmallow python3-marshmallow-sqlalchemy python3-marshmallow-enum python3-webargs python3-bcrypt python3-executing python3-pure-eval 
           apt-get -y -q install python3-reportlab python3-qrcode python3-icalendar python3-pycountry python3-xlsxwriter python3-distro
           export PATH=$PATH:$(pwd)
           bash debianalllocal.sh
           bash debiancompileindico.sh
  
  
  
  
  
  
  