name: publish
on: 
  push:
  pull_request:  
  schedule:
    - cron: "0 7 * * 2"
jobs:
  build-indico-docker-image-Debian12:
    runs-on: ubuntu-latest
    name: Debian image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 2 
    - name: Check if the Docker file was changed
      id: changed-docker-files
      uses: tj-actions/changed-files@v38
      with:
          files: Debian12

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the indico Docker image on the change of Dockerfile
      if: steps.changed-docker-files.outputs.any_changed == 'true' 
      run: |
         docker build . -f Debian12 --tag ghcr.io/andriish/indicodebian12:latest
         docker run ghcr.io/andriish/indicodebian12:latest
         docker push ghcr.io/andriish/indicodebian12:latest
    - name: Build the indico Docker image on schedule
      if: ${{ github.event_name == 'schedule' }}
      run: |
         docker build . -f Debian12 --tag ghcr.io/andriish/indicodebian12:latest
         docker run ghcr.io/andriish/indicodebian12:latest
         docker push ghcr.io/andriish/indicodebian12:latest


  build-indico-docker-image-Fedora39:
    runs-on: ubuntu-latest
    name: Fedora image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 2 
    - name: Check if the Docker file was changed
      id: changed-docker-files
      uses: tj-actions/changed-files@v38
      with:
          files: Fedora39

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the indico Docker image on the change of Dockerfile
      if: steps.changed-docker-files.outputs.any_changed == 'true' 
      run: |
         docker build . -f Fedora39 --tag ghcr.io/andriish/indicofedora39:latest
         docker run ghcr.io/andriish/indicofedora39:latest
         docker push ghcr.io/andriish/indicofedora39:latest
    - name: Build the indico Docker image on schedule
      if: ${{ github.event_name == 'schedule' }}
      run: |
         docker build . -f Fedora39 --tag ghcr.io/andriish/indicofedora39:latest
         docker run ghcr.io/andriish/indicofedora39:latest
         docker push ghcr.io/andriish/indicofedora39:latest






  run-in-indico-docker-image-Fedora39:
    name: Fedora
    runs-on: ubuntu-latest
    needs: build-indico-docker-image-Fedora39
    container:
            image: ghcr.io/andriish/indicofedora39:latest
            credentials:
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 3 
#    - uses: actions/setup-node@v4
#      with:
#        cache: 'npm'
    - name: Run
      run : |
           export PATH=$PATH:$(pwd)
           #set -x 
           sh srpmsbuild.sh  python-indico 3.2.9 --build 
  
  run-in-indico-docker-image-Debian12:
    name: Debian
    runs-on: ubuntu-latest
    needs: build-indico-docker-image-Debian12
    container:
            image: ghcr.io/andriish/indicodebian12:latest
            credentials:
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 3 
#    - uses: actions/setup-node@v4
#      with:
#        cache: 'npm'          
    - name: Run
      run : |
           set -x
           uname -a 
           cat /etc/issue
           apt-get update
           export PATH=$PATH:$(pwd)
           bash debianalllocal.sh
  
  
  
  
  
  
  